<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Item;
use App\Models\Product;
use App\Models\ProductInputField;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Product::truncate();
        Item::truncate();
        ProductInputField::truncate();

        $data = [
            ['product' => ['name' => 'Mobile Legends', 'description' => 'Top up Diamond Mobile Legends cepat dan murah.', 'categories' => ['Populer', 'Game', 'New']], 'input_fields' => [['field_label' => 'User ID', 'field_name' => 'user_id', 'field_type' => 'number', 'field_desc' => 'Masukkan User ID Anda.', 'placeholder' => '12345678', 'validation_rules' => 'required|numeric'], ['field_label' => 'Zone ID', 'field_name' => 'zone_id', 'field_type' => 'number', 'field_desc' => 'Masukkan Zone ID (4-5 digit).', 'placeholder' => '1234', 'validation_rules' => 'required|numeric|digits_between:4,5']], 'items' => [['name' => '86 Diamonds', 'price' => 24500], ['name' => '172 Diamonds', 'price' => 49000, 'discount_percentage' => 10], ['name' => 'Weekly Diamond Pass', 'price' => 28000]]],
            ['product' => ['name' => 'Free Fire', 'description' => 'Top up Diamonds Free Fire dengan cepat dan mudah.', 'categories' => ['Game', 'Populer']], 'input_fields' => [['field_label' => 'Player ID', 'field_name' => 'player_id', 'field_type' => 'number', 'field_desc' => 'Masukkan Player ID Free Fire Anda.', 'placeholder' => '123456789', 'validation_rules' => 'required|numeric']], 'items' => [['name' => '140 Diamonds', 'price' => 20000], ['name' => '355 Diamonds', 'price' => 50000], ['name' => '720 Diamonds', 'price' => 100000]]],
            ['product' => ['name' => 'PUBG Mobile', 'description' => 'Beli Unknown Cash (UC) untuk PUBG Mobile.', 'categories' => ['Game', 'Populer']], 'input_fields' => [['field_label' => 'User ID', 'field_name' => 'user_id', 'field_type' => 'number', 'field_desc' => 'Masukkan User ID PUBG Mobile Anda.', 'placeholder' => '5123456789', 'validation_rules' => 'required|numeric']], 'items' => [['name' => '60 UC', 'price' => 15000], ['name' => '325 UC', 'price' => 75000], ['name' => '660 UC', 'price' => 150000]]],
            ['product' => ['name' => 'Genshin Impact', 'description' => 'Top up Genesis Crystals untuk petualangan epik di Teyvat.', 'categories' => ['Populer', 'Game']], 'input_fields' => [['field_label' => 'UID Genshin Impact', 'field_name' => 'uid', 'field_type' => 'number', 'field_desc' => 'Masukkan UID Anda.', 'placeholder' => '800123456', 'validation_rules' => 'required|numeric|digits:9'], ['field_label' => 'Pilih Server', 'field_name' => 'server', 'field_type' => 'select', 'field_desc' => 'Pilih server game Anda.', 'field_options' => json_encode(['Asia', 'America', 'Europe', 'TW, HK, MO']), 'validation_rules' => 'required|string']], 'items' => [['name' => '60 Genesis Crystals', 'price' => 16000], ['name' => '300 + 30 Genesis Crystals', 'price' => 79000], ['name' => 'Blessing of the Welkin Moon', 'price' => 79000, 'discount_percentage' => 5]]],
            ['product' => ['name' => 'Honkai: Star Rail', 'description' => 'Top up Oneiric Shard untuk Honkai: Star Rail.', 'categories' => ['Game', 'New']], 'input_fields' => [['field_label' => 'UID', 'field_name' => 'uid', 'field_type' => 'number', 'field_desc' => 'Masukkan UID Honkai: Star Rail Anda.', 'placeholder' => '800123456', 'validation_rules' => 'required|numeric'], ['field_label' => 'Pilih Server', 'field_name' => 'server', 'field_type' => 'select', 'field_desc' => 'Pilih server game Anda.', 'field_options' => json_encode(['Asia', 'America', 'Europe']), 'validation_rules' => 'required|string']], 'items' => [['name' => '60 Oneiric Shard', 'price' => 16000], ['name' => '300 + 30 Oneiric Shard', 'price' => 79000]]],
            ['product' => ['name' => 'Call of Duty Mobile', 'description' => 'Beli CP untuk Call of Duty Mobile.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Open ID', 'field_name' => 'open_id', 'field_type' => 'text', 'field_desc' => 'Masukkan Open ID Anda.', 'placeholder' => 'ABC123XYZ456', 'validation_rules' => 'required|string']], 'items' => [['name' => '62 CP', 'price' => 10000], ['name' => '321 CP', 'price' => 50000]]],
            ['product' => ['name' => 'League of Legends: Wild Rift', 'description' => 'Top up Wild Cores untuk Wild Rift.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Riot ID', 'field_name' => 'riot_id', 'field_type' => 'text', 'field_desc' => 'Masukkan Riot ID (Contoh: Nama#TAG).', 'placeholder' => 'PemainJago#SEA', 'validation_rules' => 'required|string']], 'items' => [['name' => '125 Wild Cores', 'price' => 15000], ['name' => '400 Wild Cores', 'price' => 50000]]],
            ['product' => ['name' => 'Clash of Clans', 'description' => 'Beli Gold Pass dan penawaran khusus lainnya.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Player Tag', 'field_name' => 'player_tag', 'field_type' => 'text', 'field_desc' => 'Masukkan Player Tag Anda (Contoh: #PQR123).', 'placeholder' => '#PQR123ABC', 'validation_rules' => 'required|string']], 'items' => [['name' => 'Gold Pass', 'price' => 79000]]],
            ['product' => ['name' => 'Arena of Valor', 'description' => 'Top up Voucher AOV dengan mudah.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Open ID', 'field_name' => 'open_id', 'field_type' => 'text', 'field_desc' => 'Temukan Open ID Anda di pengaturan game.', 'placeholder' => 'ABC123XYZ456', 'validation_rules' => 'required|string']], 'items' => [['name' => '40 Voucher', 'price' => 10000], ['name' => '200 Voucher', 'price' => 50000]]],
            ['product' => ['name' => 'Stumble Guys', 'description' => 'Beli Gems dan Token untuk Stumble Guys.', 'categories' => ['Game', 'Populer']], 'input_fields' => [['field_label' => 'Nama Pengguna', 'field_name' => 'username', 'field_type' => 'text', 'field_desc' => 'Masukkan nama pengguna Stumble Guys Anda.', 'placeholder' => 'Stumbler007', 'validation_rules' => 'required|string']], 'items' => [['name' => '250 Gems', 'price' => 16000]]],
            ['product' => ['name' => 'EA Sports FC Mobile', 'description' => 'Beli FC Points untuk membangun tim impian Anda.', 'categories' => ['Game', 'New']], 'input_fields' => [['field_label' => 'FC Mobile Player ID', 'field_name' => 'player_id', 'field_type' => 'number', 'field_desc' => 'Masukkan Player ID Anda.', 'placeholder' => '100234567', 'validation_rules' => 'required|numeric']], 'items' => [['name' => '500 FC Points', 'price' => 79000]]],
            ['product' => ['name' => 'Roblox', 'description' => 'Isi ulang Robux untuk kustomisasi avatar dan item game.', 'categories' => ['Game', 'Populer']], 'input_fields' => [['field_label' => 'Username Roblox', 'field_name' => 'username', 'field_type' => 'text', 'field_desc' => 'Masukkan username Roblox Anda.', 'placeholder' => 'PemainRoblox', 'validation_rules' => 'required|string']], 'items' => [['name' => '80 Robux', 'price' => 18000], ['name' => '400 Robux', 'price' => 85000]]],
            ['product' => ['name' => 'Tower of Fantasy', 'description' => 'Top up Tanium untuk Tower of Fantasy.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'UID', 'field_name' => 'uid', 'field_type' => 'number', 'field_desc' => 'Masukkan UID Anda.', 'placeholder' => '11012345', 'validation_rules' => 'required|numeric'], ['field_label' => 'Server', 'field_name' => 'server', 'field_type' => 'select', 'field_desc' => 'Pilih server Anda.', 'field_options' => json_encode(['Southeast Asia', 'Asia-Pacific', 'North America', 'Europe']), 'validation_rules' => 'required|string']], 'items' => [['name' => '60 Tanium', 'price' => 15000]]],
            ['product' => ['name' => 'Asphalt 9', 'description' => 'Beli Token untuk mobil super impianmu.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Player ID', 'field_name' => 'player_id', 'field_type' => 'text', 'field_desc' => 'Masukkan Player ID Asphalt 9 Anda.', 'placeholder' => 'ABC-1234', 'validation_rules' => 'required|string']], 'items' => [['name' => '950 Tokens', 'price' => 149000]]],
            ['product' => ['name' => 'Hay Day', 'description' => 'Beli Diamond untuk mempercepat pertanian Anda.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Player Tag', 'field_name' => 'player_tag', 'field_type' => 'text', 'field_desc' => 'Masukkan Player Tag Anda (Contoh: #PQR123).', 'placeholder' => '#ABC123XYZ', 'validation_rules' => 'required|string']], 'items' => [['name' => '50 Diamonds', 'price' => 15000]]],

            ['product' => ['name' => 'Valorant', 'description' => 'Beli Valorant Points untuk agen dan skin favoritmu.', 'categories' => ['Game', 'New']], 'input_fields' => [['field_label' => 'Riot ID', 'field_name' => 'riot_id', 'field_type' => 'text', 'field_desc' => 'Masukkan Riot ID (Contoh: Nama#TAG).', 'placeholder' => 'PemainJago#1234', 'validation_rules' => 'required|string']], 'items' => [['name' => '125 Points', 'price' => 15000], ['name' => '420 Points', 'price' => 50000], ['name' => '1375 Points', 'price' => 150000]]],
            ['product' => ['name' => 'League of Legends PC', 'description' => 'Beli Riot Points (RP) untuk League of Legends.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Username Riot', 'field_name' => 'username', 'field_type' => 'text', 'field_desc' => 'Masukkan Username Riot Anda.', 'placeholder' => 'PemainLoL', 'validation_rules' => 'required|string']], 'items' => [['name' => '185 RP', 'price' => 25000], ['name' => '780 RP', 'price' => 100000]]],
            ['product' => ['name' => 'Point Blank', 'description' => 'Isi ulang PB Cash untuk senjata dan item terbaik.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Username Zepetto', 'field_name' => 'username', 'field_type' => 'text', 'field_desc' => 'Masukkan Username Zepetto Anda.', 'placeholder' => 'TrooperPB', 'validation_rules' => 'required|string']], 'items' => [['name' => '1200 PB Cash', 'price' => 11000], ['name' => '6000 PB Cash', 'price' => 55000]]],
            ['product' => ['name' => 'Apex Legends', 'description' => 'Beli Apex Coins untuk PC.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'EA ID', 'field_name' => 'ea_id', 'field_type' => 'text', 'field_desc' => 'Masukkan ID akun EA Anda.', 'placeholder' => 'PemainApex', 'validation_rules' => 'required|string']], 'items' => [['name' => '1000 Apex Coins', 'price' => 140000]]],
            ['product' => ['name' => 'Fortnite', 'description' => 'Beli V-Bucks untuk Fortnite.', 'categories' => ['Game']], 'input_fields' => [['field_label' => 'Epic Games ID', 'field_name' => 'epic_id', 'field_type' => 'text', 'field_desc' => 'Masukkan ID Epic Games Anda.', 'placeholder' => 'PemainFortnite', 'validation_rules' => 'required|string']], 'items' => [['name' => '1000 V-Bucks', 'price' => 120000]]],
            
            ['product' => ['name' => 'Spotify Premium', 'description' => 'Dengarkan musik tanpa iklan dengan Spotify Premium.', 'categories' => ['Populer', 'Entertainments']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP yang terdaftar di Spotify.', 'placeholder' => '081234567890', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Premium 1 Bulan', 'price' => 54990], ['name' => 'Premium 3 Bulan', 'price' => 164970]]],
            ['product' => ['name' => 'Netflix', 'description' => 'Berlangganan Netflix untuk menonton film dan serial TV tanpa batas.', 'categories' => ['Entertainments']], 'input_fields' => [['field_label' => 'Email Akun Netflix', 'field_name' => 'email', 'field_type' => 'email', 'field_desc' => 'Masukkan email yang terdaftar di Netflix.', 'placeholder' => 'anda@email.com', 'validation_rules' => 'required|email']], 'items' => [['name' => 'Paket Basic 1 Bulan', 'price' => 65000], ['name' => 'Paket Standard 1 Bulan', 'price' => 120000]]],
            ['product' => ['name' => 'YouTube Premium', 'description' => 'Nonton YouTube tanpa iklan dan putar di latar belakang.', 'categories' => ['Entertainments', 'Populer']], 'input_fields' => [['field_label' => 'Email Akun Google', 'field_name' => 'email', 'field_type' => 'email', 'field_desc' => 'Masukkan email Google Anda.', 'placeholder' => 'anda@gmail.com', 'validation_rules' => 'required|email']], 'items' => [['name' => 'Premium 1 Bulan', 'price' => 59000], ['name' => 'Premium Keluarga 1 Bulan', 'price' => 99000]]],
            ['product' => ['name' => 'Vidio', 'description' => 'Langganan Vidio Premier untuk tayangan olahraga dan hiburan eksklusif.', 'categories' => ['Entertainments']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP yang terdaftar di Vidio.', 'placeholder' => '081234567890', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Vidio Premier Platinum 30 Hari', 'price' => 39000], ['name' => 'Vidio Premier Diamond (EPL+Sports) 30 Hari', 'price' => 79000]]],
            ['product' => ['name' => 'Disney+ Hotstar', 'description' => 'Streaming film Marvel, Disney, Pixar, dan lainnya.', 'categories' => ['Entertainments']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP yang terdaftar.', 'placeholder' => '081234567890', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Langganan 1 Bulan', 'price' => 39000]]],
            ['product' => ['name' => 'WeTV', 'description' => 'Nonton drama Asia dan serial orisinal WeTV.', 'categories' => ['Entertainments']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP yang terdaftar.', 'placeholder' => '081234567890', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'VIP 1 Bulan', 'price' => 39000]]],
            ['product' => ['name' => 'iQIYI', 'description' => 'Streaming drama, film, dan anime Asia populer.', 'categories' => ['Entertainments']], 'input_fields' => [['field_label' => 'Email Akun iQIYI', 'field_name' => 'email', 'field_type' => 'email', 'field_desc' => 'Masukkan email akun iQIYI Anda.', 'placeholder' => 'anda@email.com', 'validation_rules' => 'required|email']], 'items' => [['name' => 'VIP Standard 1 Bulan', 'price' => 39000]]],
            ['product' => ['name' => 'Viu Premium', 'description' => 'Nonton drama Korea dan Asia lainnya tanpa jeda iklan.', 'categories' => ['Entertainments']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP Anda.', 'placeholder' => '081234567890', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Viu Premium 30 Hari', 'price' => 33000]]],
            ['product' => ['name' => 'Genflix', 'description' => 'Platform streaming film Indonesia dan mancanegara.', 'categories' => ['Entertainments']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP Anda.', 'placeholder' => '081234567890', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Langganan 30 Hari', 'price' => 49000]]],
            ['product' => ['name' => 'HBO GO', 'description' => 'Akses semua film dan serial HBO, Max Originals, dan lainnya.', 'categories' => ['Entertainments']], 'input_fields' => [['field_label' => 'Email', 'field_name' => 'email', 'field_type' => 'email', 'field_desc' => 'Masukkan email akun HBO GO Anda.', 'placeholder' => 'anda@email.com', 'validation_rules' => 'required|email']], 'items' => [['name' => 'Langganan 1 Bulan', 'price' => 79000]]],
            
            ['product' => ['name' => 'Voucher Google Play', 'description' => 'Beli aplikasi, game, film, dan lainnya di Google Play.', 'categories' => ['Voucher']], 'input_fields' => [['field_label' => 'Nomor WhatsApp', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Kode voucher akan dikirim ke nomor ini.', 'placeholder' => '081234567890', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Voucher Rp 20.000', 'price' => 22000], ['name' => 'Voucher Rp 50.000', 'price' => 55000]]],
            ['product' => ['name' => 'Steam Wallet Code', 'description' => 'Isi saldo Steam Wallet Anda untuk membeli ribuan game di Steam.', 'categories' => ['Voucher', 'Game']], 'input_fields' => [['field_label' => 'Email', 'field_name' => 'email', 'field_type' => 'email', 'field_desc' => 'Kode akan dikirim ke email ini.', 'placeholder' => 'anda@email.com', 'validation_rules' => 'required|email']], 'items' => [['name' => 'Steam Wallet Rp 12.000', 'price' => 15000], ['name' => 'Steam Wallet Rp 60.000', 'price' => 66000]]],
            ['product' => ['name' => 'Razer Gold', 'description' => 'Mata uang virtual terpadu untuk para gamer di seluruh dunia.', 'categories' => ['Voucher', 'Game']], 'input_fields' => [['field_label' => 'Email', 'field_name' => 'email', 'field_type' => 'email', 'field_desc' => 'PIN Razer Gold akan dikirim ke email ini.', 'placeholder' => 'anda@email.com', 'validation_rules' => 'required|email']], 'items' => [['name' => 'Razer Gold 10.000', 'price' => 11000], ['name' => 'Razer Gold 50.000', 'price' => 55000]]],
            ['product' => ['name' => 'Token Listrik PLN', 'description' => 'Beli token listrik prabayar dengan mudah.', 'categories' => ['Voucher']], 'input_fields' => [['field_label' => 'Nomor Meter/ID Pelanggan', 'field_name' => 'customer_id', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor meter atau ID pelanggan Anda.', 'placeholder' => '14123456789', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Token Rp 20.000', 'price' => 22000], ['name' => 'Token Rp 50.000', 'price' => 52000]]],
            ['product' => ['name' => 'Pulsa Telkomsel', 'description' => 'Isi ulang pulsa Telkomsel.', 'categories' => ['Voucher', 'Populer']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor Telkomsel Anda.', 'placeholder' => '0812...', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Pulsa 25.000', 'price' => 26000], ['name' => 'Pulsa 50.000', 'price' => 51000]]],
            ['product' => ['name' => 'Pulsa Indosat', 'description' => 'Isi ulang pulsa Indosat.', 'categories' => ['Voucher']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor Indosat Anda.', 'placeholder' => '0857...', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Pulsa 25.000', 'price' => 26000], ['name' => 'Pulsa 50.000', 'price' => 51000]]],
            ['product' => ['name' => 'Pulsa XL', 'description' => 'Isi ulang pulsa XL / Axis.', 'categories' => ['Voucher']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor XL/Axis Anda.', 'placeholder' => '0878...', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Pulsa 25.000', 'price' => 26000], ['name' => 'Pulsa 50.000', 'price' => 51000]]],
            ['product' => ['name' => 'Paket Data Telkomsel', 'description' => 'Beli paket data internet Telkomsel.', 'categories' => ['Voucher']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor Telkomsel Anda.', 'placeholder' => '0812...', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'OMG! 4.5 GB', 'price' => 41000]]],
            ['product' => ['name' => 'Top Up GoPay', 'description' => 'Isi saldo GoPay Anda.', 'categories' => ['Voucher']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP yang terdaftar di Gojek.', 'placeholder' => '0812...', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Saldo GoPay Rp 50.000', 'price' => 51500]]],
            ['product' => ['name' => 'Top Up DANA', 'description' => 'Isi saldo DANA Anda.', 'categories' => ['Voucher']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP yang terdaftar di DANA.', 'placeholder' => '0812...', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Saldo DANA Rp 50.000', 'price' => 51500]]],
            ['product' => ['name' => 'Top Up OVO', 'description' => 'Isi saldo OVO Anda.', 'categories' => ['Voucher']], 'input_fields' => [['field_label' => 'Nomor Handphone', 'field_name' => 'phone_number', 'field_type' => 'number', 'field_desc' => 'Masukkan nomor HP yang terdaftar di OVO.', 'placeholder' => '0812...', 'validation_rules' => 'required|numeric']], 'items' => [['name' => 'Saldo OVO Rp 50.000', 'price' => 51500]]],
        ];

        $categories = Category::pluck('id', 'name');

        foreach ($data as $productData) {
            $productName = $productData['product']['name'];
            $productSlug = Str::slug($productName);

            $mainCategoryName = $productData['product']['categories'][0];
            $mainCategoryId = $categories->get($mainCategoryName);

            $product = Product::create([
                'category_id' => $mainCategoryId, 
                'name' => $productName,
                'slug' => $productSlug,
                'description' => $productData['product']['description'],
                'thumbnail_url' => 'https://placehold.co/300x300/1e293b/94a3b8?text=' . urlencode($productName),
                'banner_url' => 'https://placehold.co/600x300/1e293b/94a3b8?text=' . urlencode($productName),
                'status' => 'active',
            ]);

            foreach ($productData['input_fields'] as $fieldData) {
                $product->inputFields()->create($fieldData);
            }

            foreach ($productData['items'] as $itemData) {
                $itemName = $itemData['name'];
                $itemData['slug'] = Str::slug($productName . ' ' . $itemName);
                $itemData['sku'] = strtoupper(Str::snake($productName . '_' . $itemName, '_'));
                $itemData['image_url'] = 'https://placehold.co/300x300/27272a/a1a1aa?text=' . urlencode($itemName);
                $product->items()->create($itemData);
            }
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
